"""Sharded JSON Lines ledgers: reviewed names, reconstruction records and inventory tags.

Layout (all tracked in git, one record per line, shard = 64 KB address band):
  config/names/<band>.jsonl           {"address","name","evidence"}                (hand-written)
  config/reconstruction/<band>.jsonl  {"kind":"function"|"fragment","address",...}  (hand-written)
  config/reconstruction/meta.json     {"game_rebuilt": false}
  config/tags/<band>.jsonl            {"address","name","category","confidence","action","create","evidence_id","source"}
  config/tags/evidence.json           {"e0001": "rule text", ...}                  (generated by build_tag_ledger.py)

Legacy monolithic files (config/ghidra_names.json, config/reconstruction.json, config/ghidra_tags.json)
are still read if present so an in-flight session loses nothing; `migrate` moves them into shards.
Never read a whole ledger into a model context: use `python tools/bsp.py lookup <address>`.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
NAMES_DIR = ROOT / 'config/names'
RECON_DIR = ROOT / 'config/reconstruction'
TAGS_DIR = ROOT / 'config/tags'
RECON_META = RECON_DIR / 'meta.json'
TAG_EVIDENCE = TAGS_DIR / 'evidence.json'
LEGACY_NAMES = ROOT / 'config/ghidra_names.json'
LEGACY_RECON = ROOT / 'config/reconstruction.json'
LEGACY_TAGS = ROOT / 'config/ghidra_tags.json'
# Several fragments may share a routine address, so reconstruction records are keyed by name too.
RECON_KEY = ('address', 'kind', 'name')


def norm(address):
    return f'{int(address, 16):08x}'


def band(address):
    return f'{int(address, 16) & ~0xffff:08x}'


def _read_dir(directory):
    records = []
    if not directory.exists():
        return records
    for path in sorted(directory.glob('*.jsonl')):
        with path.open(encoding='utf-8') as handle:
            for line in handle:
                line = line.strip()
                if line:
                    records.append(json.loads(line))
    return records


def _write_shard(path, records):
    path.parent.mkdir(parents=True, exist_ok=True)
    records = sorted(records, key=lambda r: (int(r['address'], 16), r.get('kind', '')))
    with path.open('w', encoding='utf-8', newline='\n') as handle:
        for record in records:
            handle.write(json.dumps(record, ensure_ascii=False) + '\n')


def upsert(directory, record, key=('address',)):
    """Insert or replace one record in its band shard; returns the previous record or None."""
    record = dict(record)
    record['address'] = norm(record['address'])
    path = directory / f"{band(record['address'])}.jsonl"
    existing = []
    if path.exists():
        with path.open(encoding='utf-8') as handle:
            existing = [json.loads(line) for line in handle if line.strip()]
    ident = tuple(record.get(k) for k in key)
    previous = next((r for r in existing if tuple(r.get(k) for k in key) == ident), None)
    kept = [r for r in existing if tuple(r.get(k) for k in key) != ident]
    _write_shard(path, kept + [record])
    return previous


def _merge(shards, legacy, key=('address',)):
    """Union of shard and legacy records; a legacy record wins because it is the newer in-flight edit."""
    override = {tuple(r.get(k) for k in key) for r in legacy}
    return [r for r in shards if tuple(r.get(k) for k in key) not in override] + list(legacy)


def load_names():
    shards = _read_dir(NAMES_DIR)
    legacy = json.loads(LEGACY_NAMES.read_text(encoding='utf-8')) if LEGACY_NAMES.exists() else []
    for r in legacy:
        r['address'] = norm(r['address'])
    return sorted(_merge(shards, legacy), key=lambda r: int(r['address'], 16))


def load_reconstruction():
    shards = _read_dir(RECON_DIR)
    meta = json.loads(RECON_META.read_text(encoding='utf-8')) if RECON_META.exists() else {}
    legacy = json.loads(LEGACY_RECON.read_text(encoding='utf-8')) if LEGACY_RECON.exists() else {}
    legacy_rows = [dict(r, kind='function') for r in legacy.get('functions', [])] + \
                  [dict(r, kind='fragment') for r in legacy.get('fragments', [])]
    for r in legacy_rows:
        r['address'] = norm(r['address'])
    rows = _merge(shards, legacy_rows, key=RECON_KEY)
    rows.sort(key=lambda r: int(r['address'], 16))
    result = {'game_rebuilt': meta.get('game_rebuilt', legacy.get('game_rebuilt', False)),
              'functions': [], 'fragments': []}
    for r in rows:
        kind = r.get('kind', 'function')
        row = {k: v for k, v in r.items() if k != 'kind'}
        result['fragments' if kind == 'fragment' else 'functions'].append(row)
    return result


def load_tags():
    evidence = json.loads(TAG_EVIDENCE.read_text(encoding='utf-8')) if TAG_EVIDENCE.exists() else {}
    shards = []
    for r in _read_dir(TAGS_DIR):
        r = dict(r)
        r['evidence'] = evidence.get(r.pop('evidence_id', ''), '')
        shards.append(r)
    legacy = json.loads(LEGACY_TAGS.read_text(encoding='utf-8')) if LEGACY_TAGS.exists() else []
    return sorted(_merge(shards, legacy), key=lambda r: int(r['address'], 16))


def write_tags(entries):
    """Replace the generated tag shards wholesale (evidence strings deduplicated into evidence.json)."""
    TAGS_DIR.mkdir(parents=True, exist_ok=True)
    for old in TAGS_DIR.glob('*.jsonl'):
        old.unlink()
    ids = {}
    grouped = {}
    for e in sorted(entries, key=lambda r: int(r['address'], 16)):
        text = e.get('evidence', '')
        if text not in ids:
            ids[text] = f'e{len(ids) + 1:04d}'
        row = {k: v for k, v in e.items() if k != 'evidence'}
        row['address'] = norm(row['address'])
        row['evidence_id'] = ids[text]
        grouped.setdefault(band(row['address']), []).append(row)
    for name, rows in grouped.items():
        _write_shard(TAGS_DIR / f'{name}.jsonl', rows)
    TAG_EVIDENCE.write_text(json.dumps({v: k for k, v in ids.items()}, indent=1, ensure_ascii=False) + '\n',
                            encoding='utf-8', newline='\n')
    return len(grouped), len(ids)


def migrate(prune=True):
    """Move legacy monolithic ledgers into shards. Idempotent; safe to run before every commit."""
    moved = {'names': 0, 'functions': 0, 'fragments': 0, 'tags': 0}
    if LEGACY_NAMES.exists():
        for r in json.loads(LEGACY_NAMES.read_text(encoding='utf-8')):
            upsert(NAMES_DIR, r)
            moved['names'] += 1
        if prune:
            LEGACY_NAMES.unlink()
    if LEGACY_RECON.exists():
        legacy = json.loads(LEGACY_RECON.read_text(encoding='utf-8'))
        for r in legacy.get('functions', []):
            upsert(RECON_DIR, dict(r, kind='function'), key=RECON_KEY)
            moved['functions'] += 1
        for r in legacy.get('fragments', []):
            upsert(RECON_DIR, dict(r, kind='fragment'), key=RECON_KEY)
            moved['fragments'] += 1
        RECON_DIR.mkdir(parents=True, exist_ok=True)
        if not RECON_META.exists() or 'game_rebuilt' in legacy:
            RECON_META.write_text(json.dumps({'game_rebuilt': legacy.get('game_rebuilt', False)}, indent=1) + '\n',
                                  encoding='utf-8', newline='\n')
        if prune:
            LEGACY_RECON.unlink()
    if LEGACY_TAGS.exists():
        legacy = json.loads(LEGACY_TAGS.read_text(encoding='utf-8'))
        current = {r['address']: r for r in load_tags() if TAGS_DIR.exists()}
        for r in legacy:
            current[norm(r['address'])] = r
        write_tags(list(current.values()))
        moved['tags'] = len(legacy)
        if prune:
            LEGACY_TAGS.unlink()
    return moved
