#include "bsp/native_unit_wake_copy.hpp"

namespace bsp {
// Literal complete Original body: 456 bytes, 135 instructions; SHA-256
// a262b08eda2774d3f406cd56fa1f9a44f6447ae96d10e3d7efec9d3bf6859ecd.
// Direct caller 00815EAA supplies new+BD0 and old+BD0. No external calls,
// relocations, globals or provider boundary exist inside this entry.
// Keep the integer head store before all samples and the original four-pass
// x87 schedule, including MOV EDI,EDI and the register increments mid-pass.
__declspec(naked) void __fastcall copy_native_unit_wake_00815680(
    void*, void*, const void*) noexcept {
    __asm {
        push esi
        mov esi, dword ptr [esp + 8]
        mov eax, dword ptr [esi + 0x3c8]
        mov dword ptr [ecx + 0x3c8], eax
        lea edx, [esi + 0x14]
        lea eax, [ecx + 0xc]
        sub esi, ecx
        mov ecx, 4
        mov edi, edi
    copy_samples:
        fld dword ptr [edx - 0xc]
        fstp dword ptr [eax - 4]
        fld dword ptr [esi + eax]
        fstp dword ptr [eax]
        fld dword ptr [edx - 4]
        fstp dword ptr [eax + 4]
        fld dword ptr [edx]
        fstp dword ptr [eax + 8]
        fld dword ptr [edx + 4]
        fstp dword ptr [eax + 0xc]
        fld dword ptr [edx + 8]
        fstp dword ptr [eax + 0x10]
        fld dword ptr [edx + 0xc]
        fstp dword ptr [eax + 0x14]
        fld dword ptr [edx + 0x10]
        fstp dword ptr [eax + 0x18]
        fld dword ptr [edx + 0x14]
        fstp dword ptr [eax + 0x1c]
        fld dword ptr [edx + 0x18]
        fstp dword ptr [eax + 0x20]
        fld dword ptr [edx + 0x1c]
        fstp dword ptr [eax + 0x24]
        fld dword ptr [edx + 0x20]
        fstp dword ptr [eax + 0x28]
        fld dword ptr [edx + 0x24]
        fstp dword ptr [eax + 0x2c]
        fld dword ptr [edx + 0x28]
        fstp dword ptr [eax + 0x30]
        fld dword ptr [edx + 0x2c]
        fstp dword ptr [eax + 0x34]
        fld dword ptr [edx + 0x30]
        fstp dword ptr [eax + 0x38]
        fld dword ptr [edx + 0x34]
        fstp dword ptr [eax + 0x3c]
        fld dword ptr [edx + 0x38]
        fstp dword ptr [eax + 0x40]
        fld dword ptr [edx + 0x3c]
        fstp dword ptr [eax + 0x44]
        fld dword ptr [edx + 0x40]
        fstp dword ptr [eax + 0x48]
        fld dword ptr [edx + 0x44]
        fstp dword ptr [eax + 0x4c]
        fld dword ptr [edx + 0x48]
        fstp dword ptr [eax + 0x50]
        fld dword ptr [edx + 0x4c]
        fstp dword ptr [eax + 0x54]
        fld dword ptr [edx + 0x50]
        fstp dword ptr [eax + 0x58]
        fld dword ptr [edx + 0x54]
        fstp dword ptr [eax + 0x5c]
        fld dword ptr [edx + 0x58]
        fstp dword ptr [eax + 0x60]
        fld dword ptr [edx + 0x5c]
        fstp dword ptr [eax + 0x64]
        fld dword ptr [edx + 0x60]
        fstp dword ptr [eax + 0x68]
        fld dword ptr [edx + 0x64]
        fstp dword ptr [eax + 0x6c]
        fld dword ptr [edx + 0x68]
        fstp dword ptr [eax + 0x70]
        fld dword ptr [edx + 0x6c]
        fstp dword ptr [eax + 0x74]
        fld dword ptr [edx + 0x70]
        fstp dword ptr [eax + 0x78]
        fld dword ptr [edx + 0x74]
        fstp dword ptr [eax + 0x7c]
        fld dword ptr [edx + 0x78]
        fstp dword ptr [eax + 0x80]
        fld dword ptr [edx + 0x7c]
        fstp dword ptr [eax + 0x84]
        fld dword ptr [edx + 0x80]
        fstp dword ptr [eax + 0x88]
        fld dword ptr [edx + 0x84]
        fstp dword ptr [eax + 0x8c]
        fld dword ptr [edx + 0x88]
        fstp dword ptr [eax + 0x90]
        fld dword ptr [edx + 0x8c]
        fstp dword ptr [eax + 0x94]
        fld dword ptr [edx + 0x90]
        fstp dword ptr [eax + 0x98]
        fld dword ptr [edx + 0x94]
        fstp dword ptr [eax + 0x9c]
        add edx, 0xf0
        fld dword ptr [edx - 0x58]
        add eax, 0xf0
        sub ecx, 1
        fstp dword ptr [eax - 0x50]
        fld dword ptr [edx - 0x54]
        fstp dword ptr [eax - 0x4c]
        fld dword ptr [edx - 0x50]
        fstp dword ptr [eax - 0x48]
        fld dword ptr [edx - 0x4c]
        fstp dword ptr [eax - 0x44]
        fld dword ptr [edx - 0x48]
        fstp dword ptr [eax - 0x40]
        fld dword ptr [edx - 0x44]
        fstp dword ptr [eax - 0x3c]
        fld dword ptr [edx - 0x40]
        fstp dword ptr [eax - 0x38]
        fld dword ptr [edx - 0x3c]
        fstp dword ptr [eax - 0x34]
        fld dword ptr [edx - 0x38]
        fstp dword ptr [eax - 0x30]
        fld dword ptr [edx - 0x34]
        fstp dword ptr [eax - 0x2c]
        fld dword ptr [edx - 0x30]
        fstp dword ptr [eax - 0x28]
        fld dword ptr [edx - 0x2c]
        fstp dword ptr [eax - 0x24]
        fld dword ptr [edx - 0x28]
        fstp dword ptr [eax - 0x20]
        fld dword ptr [edx - 0x24]
        fstp dword ptr [eax - 0x1c]
        fld dword ptr [edx - 0x20]
        fstp dword ptr [eax - 0x18]
        fld dword ptr [edx - 0x1c]
        fstp dword ptr [eax - 0x14]
        fld dword ptr [edx - 0x18]
        fstp dword ptr [eax - 0x10]
        fld dword ptr [edx - 0x14]
        fstp dword ptr [eax - 0xc]
        fld dword ptr [edx - 0x10]
        fstp dword ptr [eax - 8]
        jnz copy_samples
        pop esi
        ret 4
    }
}
} // namespace bsp
