// Generated by local/emit_deliverables.py from the installed, read-only
// scripts/datatables/classtables/{arcade,realistic}/reconclasses.lua.
// Do not hand-edit; see docs/SENSOR_TABLE_DATA.md for provenance.

#include "bsp/sensor_table_data.hpp"

namespace bsp {
namespace {

using C = SensorCategory;

const ReconAuthoredEntry kArcade1_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_out, {1200.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade1_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade2_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {6000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {6000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::periscope_out, {1200.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade2_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {6000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kArcade3_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_in, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_in, {2500.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::periscope_out, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {2500.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::underwater, {660.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {1660.0, 1.0, 2, 2, true, 0.7853981633974483}},
};
const ReconAuthoredRing kArcade3_rings[] = {
    {C::surface, {1000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {2500.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, true, 0.785398, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade4_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {5000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {5000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::periscope_in, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_in, {2500.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::periscope_out, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {2500.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::underwater, {660.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {1660.0, 1.0, 2, 2, true, 0.7853981633974483}},
};
const ReconAuthoredRing kArcade4_rings[] = {
    {C::surface, {1000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {2500.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, true, 0.785398, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {5000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kArcade5_entries[] = {
    {C::air, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade5_rings[] = {
    {C::air, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade6_entries[] = {
    {C::air, C::air, {5000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::surface, {5000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::periscope_in, {750.0, 1.0, 2, 2, false, 0.0}},
    {C::air, C::periscope_out, {750.0, 1.0, 2, 2, false, 0.0}},
    {C::air, C::underwater, {495.0, 1.0, 2, 2, false, 0.0}},
};
const ReconAuthoredRing kArcade6_rings[] = {
    {C::air, {750.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::air, {5000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade7_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_in, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::surface, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::periscope_in, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::periscope_out, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::underwater, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::periscope_out, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::periscope_out, C::periscope_in, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::periscope_out, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::underwater, {1800.0, 0.2, 2, 2, false, 0.0}},
    {C::underwater, C::surface, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::periscope_in, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::periscope_out, {1800.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::underwater, {1800.0, 1.0, 2, 2, false, 0.0}},
};
const ReconAuthoredRing kArcade7_rings[] = {
    {C::surface, {1800.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::periscope_in, {1800.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::periscope_out, {1800.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::periscope_out, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::underwater, {1800.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
};

const ReconAuthoredEntry kArcade8_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade8_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade9_entries[] = {
    {C::surface, C::air, {6000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {6000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade9_rings[] = {
    {C::surface, {6000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kArcade10_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {10000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 1, 1, false, 0.0}},
};
const ReconAuthoredRing kArcade10_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {10000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kArcade11_entries[] = {
    {C::surface, C::air, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {5000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {4000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {5000.0, 1.0, 1, 1, false, 0.0}},
};
const ReconAuthoredRing kArcade11_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {5000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kArcade12_entries[] = {
    {C::surface, C::air, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::air, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::surface, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::surface, {0.0, 0.0, 0, 0, false, 0.0}},
};
const ReconAuthoredRing kArcade12_rings[] = {
    {C::surface, {0.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {0.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 0}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kRealistic1_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_out, {3000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic1_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic2_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {20000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {20000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::periscope_out, {3000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic2_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {20000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kRealistic3_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_in, {10000.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {10000.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::underwater, {2640.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {6640.0, 1.0, 2, 2, true, 0.7853981633974483}},
};
const ReconAuthoredRing kRealistic3_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {10000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, true, 0.785398, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic4_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {10000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_in, {10000.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {10000.0, 1.0, 2, 2, true, 0.7853981633974483}},
    {C::surface, C::underwater, {2640.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {6640.0, 1.0, 2, 2, true, 0.7853981633974483}},
};
const ReconAuthoredRing kRealistic4_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {10000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, true, 0.785398, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {10000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kRealistic5_entries[] = {
    {C::air, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic5_rings[] = {
    {C::air, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic6_entries[] = {
    {C::air, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::air, C::periscope_in, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::air, C::periscope_out, {1000.0, 1.0, 2, 2, false, 0.0}},
    {C::air, C::underwater, {660.0, 1.0, 2, 2, false, 0.0}},
};
const ReconAuthoredRing kRealistic6_rings[] = {
    {C::air, {1000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::air, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic7_entries[] = {
    {C::surface, C::air, {9000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {9000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::surface, C::underwater, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::surface, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_in, C::underwater, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::air, {9000.0, 1.0, 2, 0, false, 0.0}},
    {C::periscope_out, C::surface, {9000.0, 1.0, 2, 0, false, 0.0}},
    {C::periscope_out, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::periscope_out, C::underwater, {4000.0, 0.2, 2, 2, false, 0.0}},
    {C::underwater, C::surface, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::periscope_in, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::periscope_out, {4000.0, 1.0, 2, 2, false, 0.0}},
    {C::underwater, C::underwater, {4000.0, 1.0, 2, 2, false, 0.0}},
};
const ReconAuthoredRing kRealistic7_rings[] = {
    {C::surface, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::surface, {9000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::periscope_in, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::periscope_out, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
    {C::periscope_out, {9000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::underwater, {4000.0, {0x00000000u, 0x3f800000u, 0x00000000u, 0x3f800000u}, false, 0.0, 2}},   // COL {0, 1, 0, 1}
};

const ReconAuthoredEntry kRealistic8_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic8_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic9_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic9_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
};

const ReconAuthoredEntry kRealistic10_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {20000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {20000.0, 1.0, 1, 1, false, 0.0}},
};
const ReconAuthoredRing kRealistic10_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {20000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kRealistic11_entries[] = {
    {C::surface, C::air, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::air, {20000.0, 1.0, 1, 1, false, 0.0}},
    {C::surface, C::surface, {10000.0, 1.0, 2, 0, false, 0.0}},
    {C::surface, C::surface, {20000.0, 1.0, 1, 1, false, 0.0}},
};
const ReconAuthoredRing kRealistic11_rings[] = {
    {C::surface, {10000.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {20000.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 1}},   // COL {1, 0, 0, 1}
};

const ReconAuthoredEntry kRealistic12_entries[] = {
    {C::surface, C::air, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::air, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::surface, {0.0, 0.0, 0, 0, false, 0.0}},
    {C::surface, C::surface, {0.0, 0.0, 0, 0, false, 0.0}},
};
const ReconAuthoredRing kRealistic12_rings[] = {
    {C::surface, {0.0, {0x00000000u, 0x00000000u, 0x3f800000u, 0x3f800000u}, false, 0.0, 0}},   // COL {0, 0, 1, 1}
    {C::surface, {0.0, {0x3f800000u, 0x00000000u, 0x00000000u, 0x3f800000u}, false, 0.0, 0}},   // COL {1, 0, 0, 1}
};

const ReconClassSource kArcadeClasses[] = {
    {1, "Normal Ship (Cargo ship, Torpedoboat)", kArcade1_entries, std::size(kArcade1_entries),
     kArcade1_rings, std::size(kArcade1_rings)},
    {2, "Radar ship (Battleship, Carrier)", kArcade2_entries, std::size(kArcade2_entries),
     kArcade2_rings, std::size(kArcade2_rings)},
    {3, "Sonar ship (Destroyer)", kArcade3_entries, std::size(kArcade3_entries),
     kArcade3_rings, std::size(kArcade3_rings)},
    {4, "Ship with radar and sonar (Cruiser - TONE)", kArcade4_entries, std::size(kArcade4_entries),
     kArcade4_rings, std::size(kArcade4_rings)},
    {5, "Normal plane", kArcade5_entries, std::size(kArcade5_entries),
     kArcade5_rings, std::size(kArcade5_rings)},
    {6, "Recon plane", kArcade6_entries, std::size(kArcade6_entries),
     kArcade6_rings, std::size(kArcade6_rings)},
    {7, "Normal submarine", kArcade7_entries, std::size(kArcade7_entries),
     kArcade7_rings, std::size(kArcade7_rings)},
    {8, "Ground unit w/o radar", kArcade8_entries, std::size(kArcade8_entries),
     kArcade8_rings, std::size(kArcade8_rings)},
    {9, "Ground unit with high vision (Observation post)", kArcade9_entries, std::size(kArcade9_entries),
     kArcade9_rings, std::size(kArcade9_rings)},
    {10, "Ground unit with radar (Radar station)", kArcade10_entries, std::size(kArcade10_entries),
     kArcade10_rings, std::size(kArcade10_rings)},
    {11, "Ground unit with small radar (Airfield)", kArcade11_entries, std::size(kArcade11_entries),
     kArcade11_rings, std::size(kArcade11_rings)},
    {12, "Units with no recon", kArcade12_entries, std::size(kArcade12_entries),
     kArcade12_rings, std::size(kArcade12_rings)},
};

const ReconClassSource kRealisticClasses[] = {
    {1, "Normal Ship (Cargo ship, Torpedoboat)", kRealistic1_entries, std::size(kRealistic1_entries),
     kRealistic1_rings, std::size(kRealistic1_rings)},
    {2, "Radar ship (Battleship, Carrier)", kRealistic2_entries, std::size(kRealistic2_entries),
     kRealistic2_rings, std::size(kRealistic2_rings)},
    {3, "Sonar ship (Destroyer)", kRealistic3_entries, std::size(kRealistic3_entries),
     kRealistic3_rings, std::size(kRealistic3_rings)},
    {4, "Ship with radar and sonar (Cruiser - TONE)", kRealistic4_entries, std::size(kRealistic4_entries),
     kRealistic4_rings, std::size(kRealistic4_rings)},
    {5, "Normal plane", kRealistic5_entries, std::size(kRealistic5_entries),
     kRealistic5_rings, std::size(kRealistic5_rings)},
    {6, "Recon plane", kRealistic6_entries, std::size(kRealistic6_entries),
     kRealistic6_rings, std::size(kRealistic6_rings)},
    {7, "Normal submarine", kRealistic7_entries, std::size(kRealistic7_entries),
     kRealistic7_rings, std::size(kRealistic7_rings)},
    {8, "Ground unit w/o radar", kRealistic8_entries, std::size(kRealistic8_entries),
     kRealistic8_rings, std::size(kRealistic8_rings)},
    {9, "Ground unit with high vision (Observation post)", kRealistic9_entries, std::size(kRealistic9_entries),
     kRealistic9_rings, std::size(kRealistic9_rings)},
    {10, "Ground unit with radar (Radar station)", kRealistic10_entries, std::size(kRealistic10_entries),
     kRealistic10_rings, std::size(kRealistic10_rings)},
    {11, "Ground unit with small radar (Airfield)", kRealistic11_entries, std::size(kRealistic11_entries),
     kRealistic11_rings, std::size(kRealistic11_rings)},
    {12, "Units with no recon", kRealistic12_entries, std::size(kRealistic12_entries),
     kRealistic12_rings, std::size(kRealistic12_rings)},
};

} // namespace

const ReconClassSource* recon_class_source(ReconTableVariant variant,
                                           int recon_class_id) noexcept {
    const ReconClassSource* table =
        variant == ReconTableVariant::realistic ? kRealisticClasses
                                                : kArcadeClasses;
    for (std::size_t i = 0; i < kReconClassCount; ++i) {
        if (table[i].recon_class_id == recon_class_id) {
            return &table[i];
        }
    }
    return nullptr;
}

SensorClassTable build_sensor_class_table_008082a0(ReconTableVariant variant,
                                                   int recon_class_id) {
    SensorClassTable out;
    const ReconClassSource* src = recon_class_source(variant, recon_class_id);
    if (src == nullptr) {
        return out;   // 008082CD/008082FE: a missing row leaves 56 empty lists
    }
    for (std::size_t i = 0; i < src->entry_count; ++i) {
        const ReconAuthoredEntry& e = src->entries[i];
        out.list(e.observer, e.subject)
            .push_back(sensor_entry_from_lua_row_008085c0(e.row));
    }
    for (std::size_t i = 0; i < src->ring_count; ++i) {
        const ReconAuthoredRing& r = src->rings[i];
        out.gui_rings[static_cast<std::size_t>(static_cast<int>(r.observer))]
            .push_back(sensor_ring_from_lua_row_00808791(r.row));
    }
    return out;
}

} // namespace bsp
